### ISSUE TITLE
Keep get "write EPIPE" and "ECONNRESET" after upgrade from 0.30.5 to 2.3.1

### ISSUE THREAD

**Issue by davidNHK** [DataDog/dd-trace-js#1915]
**Describe the bug**

Error stack

```js
Error: write EPIPE
  File "internal/stream_base_commons.js", line 156, col 25, in afterWriteDispatched
  File "internal/stream_base_commons.js", line 147, col 3, in writeGeneric
  File "net.js", line 787, col 11, in Socket._writeGeneric
  File "net.js", line 799, col 8, in Socket._write
  File "internal/streams/writable.js", line 358, col 12, in writeOrBuffer
  File "internal/streams/writable.js", line 303, col 10, in Socket.Writable.write
  File "/deploy/neat-business-signup/node_modules/ioredis/built/redis/index.js", line 679, col 33, in Redis.sendCommand
    (stream || this.stream).write(command.toWritable());
  File "/deploy/neat-business-signup/node_modules/dd-trace/packages/datadog-instrumentations/src/ioredis.js", line 35, col 26, in Redis.sendCommand
    return sendCommand.apply(this, arguments)
  File "/deploy/neat-business-signup/node_modules/ioredis/built/redis/event_handler.js", line 257, col 26, in undefined.<anonymous>
    self.sendCommand(item.command, item.stream);
  File "/deploy/neat-business-signup/node_modules/ioredis/built/redis/event_handler.js", line 46, col 39, in Socket.<anonymous>
    exports.readyHandler(self)();
```

We have ioRedis in our system. and this error is come from ioRedis on `datadog-instrumentations`.

Ant clue on given above error ? 

**Environment**

* **Operation system:** Linux
* **Node version:** 14
* **Tracer version:** 2.3.1
* **Agent version:** 7.33.1

**Comment by rochdev** [comment]
The error seems to be coming from a bound event emitter from the `net` plugin. We've just merged a new version of that plugin in #1913 that no longer binds the emitter, which should hopefully fix the issue. If it doesn't, at the very least it should clean up the stack trace which will help isolating the issue.

If you don't want to wait for the next release it should be enough to use `DD_TRACE_NET_ENABLED=false` to test that assumption.

**Comment by dmattia** [comment]
Of note, I also saw a number of `ECONNRESET` errors after bumping up to 2.3.1, but setting `DD_TRACE_NET_ENABLED=false` did not solve the issue. I moved back down to `=2.0.0-appsec-beta.5` that we had been using previously, which fixed the issue, but I don't love the fact that we're back on a beta versionl.

**Comment by bengl** [comment]
@davidNHK @dmattia Could you try with v2.4.2 and see if the issue persists?

**Comment by dmattia** [comment]
Things have been working for a few days for me on v2.4.2 👍

**Comment by bengl** [comment]
@dmattia great! I'll close this issue then. Please feel free to comment/reopen if it comes up again.
