### ISSUE TITLE
Newest dd-trace versions 2.13.0 / 3.0.0 failing completely on Node 16.17.0 with native ESM module

### ISSUE THREAD

**Issue by robaca** [DataDog/dd-trace-js#2311]
**Expected behaviour**
Run a native ESM node module js file with the following command should succeed:
```
node --loader dd-trace/loader-hook.mjs some/index.mjs
```

Content of `some/index.mjs`:
```
import path from 'path'

export {}
```

Content of `package.json`:
```
{
  "dependencies": {
    "dd-trace": "^3.0.0"
  }
}
```

**Actual behaviour**
I get the following error message:
```
node:1) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, getSource
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_RETURN_PROPERTY_VALUE]: Expected undefined or a fully resolved URL string to be returned for the "responseURL" from the "dd-trace/loader-hook.mjs 'load'" function but got instance of String.
    at new NodeError (node:internal/errors:387:5)
    at ESMLoader.load (node:internal/modules/esm/loader:639:13)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:464:11) {
  code: 'ERR_INVALID_RETURN_PROPERTY_VALUE'
}
```

**Steps to reproduce**

see above

**Environment**

* **Operation system:** Linux
* **Node.js version:** 16.17.0
* **Tracer version:** 2.13.0 / 3.0.0

**Comment by rochdev** [comment]
Fixed in #2329 and will be in the next release.

**Comment by guidev** [comment]
I still get the following error on node 16.17.0 with the latest version:


```
    "import-in-the-middle": {
      "version": "1.3.2",
      "resolved": "https://registry.npmjs.org/import-in-the-middle/-/import-in-the-middle-1.3.2.tgz",
      "integrity": "sha512-TW2Zor1MmNL2e051F+B9pK3fPqMWUSBXzWjcJqfb1VBJgB+89OBh2n2rj3c16EGYeDJpt4eBdrOnrjAIR/6oRA==",
      "requires": {
        "module-details-from-path": "^1.0.3"
      }
    },

```

`node --loader dd-trace/loader-hook.mjs dist/app.js`

```



(node:9259) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9259) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, getSource
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
    at new NodeError (node:internal/errors:372:5)
    at fileURLToPath (node:internal/url:1422:11)
    at checkIfDisallowedImport (node:internal/modules/esm/resolve:1061:23)
    at defaultResolve (node:internal/modules/esm/resolve:1189:23)
    at resolve (file:///var/app/current/node_modules/import-in-the-middle/hook.mjs:58:21)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_INVALID_URL_SCHEME'
} 


```

**Comment by rochdev** [comment]
@uurien Is it possible that the fix was incomplete?
