### ISSUE TITLE
pg is not being instrumented properly

### ISSUE THREAD

**Issue by AbdelrhmanAbdelhamed** [DataDog/dd-trace-js#3239]
**Expected behaviour**

`pgQuery` internal functions to be preserved (.submit, _attach, ... etc)
```
submit(connection) {
    this.connection = connection
    this._attach()
    connection.query(this.text)
  }
```
**Actual behaviour**

Due to this line here

https://github.com/DataDog/dd-trace-js/blob/7b645b910596816dd39446d242a95e142d3bcf77/packages/datadog-instrumentations/src/pg.js#L36-L37

https://github.com/DataDog/dd-trace-js/pull/3212/files

`.submit` is gone along with other internal functions which messed up the Submittable interface of client.query

which is expected by pg package here
https://github.com/brianc/node-postgres/blob/46cfb25baf8fdba87f71c3888fcb0021eaf829d3/packages/pg/lib/client.js#L511-L513

https://node-postgres.com/apis/client#clientquery
![image](https://github.com/DataDog/dd-trace-js/assets/10197522/9f636600-9aa6-42d8-95c1-eaefa8499810)

and that causes an issue with compatibility with other libraries like pg-copy-streams see [related issue here](https://github.com/brianc/node-pg-copy-streams/issues/150)

**Steps to reproduce**
```
require('dd-trace').init();
const knex = require('knex')({
  client: 'pg',
  connection: 'postgres://127.0.0.1:5432/postgres',
  searchPath: ['public'],
});
const copyTo = require('./copy-to.js');

(async function() {
const client = await knex.client.acquireConnection();
const datastream = client.query(copyTo(`COPY (SELECT generate_series(1,10)) TO STDOUT`))
datastream.pipe(process.stdout)
})()
```

**Environment**

* **Operation system:** Linux
* **Node.js version:** 16.16.0
* **Tracer version:** 3.22.1+ 
* **Agent version:**
* **Relevant library versions:**

**Comment by elldritch** [comment]
This bug is also happening for us. Our snippet is at https://github.com/brianc/node-pg-copy-streams/issues/150#issuecomment-1600091147

**Comment by jzumbrun** [comment]
This issue is also affecting our systems since we are using pg-query-stream, which uses:
```
const stream = client.query(query);
stream.on('end', client.release);
stream.pipe(pipeFunc).pipe(JSONStream.stringify()).pipe(res);
```
I get stream.on is not a function when dd-trace is enabled.

**Comment by tlhunter** [comment]
Thanks for the bug report.

Ironically, this change was made to fix support for sql-template-tags.

It looks like the problem is that prototype methods aren't available so the correct solution might be to still create a shallow clone but then set the prototype of the cloned object to that of the original object.

I'll try to make that change soon.

**Comment by AbdelrhmanAbdelhamed** [comment]
> Thanks for the bug report.
> 
> Ironically, this change was made to fix support for sql-template-tags.
> 
> It looks like the problem is that prototype methods aren't available so the correct solution might be to still create a shallow clone but then set the prototype of the cloned object to that of the original object.
> 
> I'll try to make that change soon.

 `text` property has only getter with no setter which is why the shallow clone was introduced as a quick fix. Maybe a better solution is to provide a setter so it could be written/overridden with no issue (maybe using Object.defineProperty?)

**Comment by tlhunter** [comment]
Will hopefully be fixed here: https://github.com/DataDog/dd-trace-js/pull/3307

**Comment by tlhunter** [comment]
Versions [v2.38.0](https://github.com/DataDog/dd-trace-js/releases/tag/v2.38.0), [v3.25.0](https://github.com/DataDog/dd-trace-js/releases/tag/v3.25.0), and [v4.4.0](https://github.com/DataDog/dd-trace-js/releases/tag/v4.4.0) should now be available on npm and this issue should be fixed.

**Comment by comp615** [comment]
@tlhunter this is still broken in 3.32 and caused us a full day of production issues

**Comment by tlhunter** [comment]
@comp615 please provide a stack trace and a list of packages related to your pg setup (ORMs, etc.) If you can provide a repro then that would help a lot.

**Comment by comp615** [comment]
@tlhunter We're using this:
```
import { from as copyFrom } from 'pg-copy-streams';
```

The engineer who found this is out this week but said:
I ended up adding some instrumentation to the copyFrom class from the package we were using and I ended up noticing that the instance object looked like it was being clobbered in the cases when the failure was occurring. I then noticed that the instance object in the good one had some datadog injected fields.... hmmm. I then went ahead and turned off datadog on my local dev (thankfully i have the tracer enabled locally, not the agent of course though) and voila, 100% success rate!! So I then reverted the dd-trace package and turned the tracer back on to ensure it would still work and it does.

**Comment by comp615** [comment]
@tlhunter I spent a long time looking at this again today.

For stream based queries, i.e. that shown above. It seems like the new code is potentially clobbering callback bindings. From what I see, when the stream's `finish` event is called, thus triggering `_final` ([here](https://github.com/brianc/node-pg-copy-streams/blob/935967c0aec3ce968e07e0eaaf88306cdcee5eb3/copy-from.js#L82)), the callback binding becomes incorrect. The prototype is still a `CopyStreamQuery`, but all the instance data and callbacks are lost. My understanding is the new hack preserves the prototype but not the instance data.

It may be worth stepping back and figuring out a better way to store this text and get it between the plugin and instrumentation as this continues to be a recurring issue. Would something like a global WeakMap work? Can the architecture overall be reworked to read/write at a different time? It would seem like a much safer rule to NEVER interfere or rewrite items that are passing through dd-trace as these will always be hard to make work with other things that might be doing the same

Reverting #3212 locally removes the problem.

**Comment by ikkala** [comment]
One mine to step is also pg-cursor. [Documentation says](https://node-postgres.com/apis/cursor) about Cursor constructor:
> [new Cursor(text: String, values: Any[][, config: CursorQueryConfig])](https://node-postgres.com/apis/cursor#new-cursortext-string-values-any-config-cursorqueryconfig)
Instantiates a new Cursor. A cursor is an instance of Submittable and **should be passed directly to the client.query** method.

I debugged quite a while why dd-trace broke our code but then I realize above documentation.

The following works without dd-trace but is never returning from the last iteration of `cursor.read` with dd-trace:
```
        const cursor = new Cursor("SELECT column1 FROM table1");
        client.query(cursor); // Note: not using return value of "query" as "cursor"
        // "If the cursor has read to the end of the result sets all subsequent calls to cursor#read will return a 0 length array of rows."
        rows = [];
        do {
            rows = await cursor.read(100);
            console.log("Rows:", rows);
        } while (rows.length > 0);

```

To fix that work with dd-trace, we have to:
```
        const cursorInstance = new Cursor("SELECT column1 FROM table1");
        const cursor = client.query(cursorInstance); // Note: using return value of "query" as "cursor"
            // "If the cursor has read to the end of the result sets all subsequent calls to cursor#read will return a 0 length array of rows."
        rows = [];
        do {
            rows = await cursor.read(100);
            console.log("Rows:", rows);
        } while (rows.length > 0);

```

Not sure if this can be thought as a bug or not from in dd-trace?

**Comment by comp615** [comment]
Looks like #3603, now merged, is trying to solve this!

**Comment by ikkala** [comment]
Now the following also works with "dd-trace": "4.16.0":
```
const cursor = new Cursor("SELECT column1 FROM table1");
client.query(cursor); // Note: not using return value of "query" as "cursor"
// "If the cursor has read to the end of the result sets all subsequent calls to cursor#read will
// return a 0 length array of rows."
rows = [];
do {
    rows = await cursor.read(100);
    console.log("Rows:", rows);
} while (rows.length > 0);
```
:+1:
