### ISSUE TITLE
Early exit when using dd-trace/loader-hook.mjs and cyclic dependencies

### ISSUE THREAD

**Issue by pwwolf** [DataDog/dd-trace-js#3595]
**Expected behaviour**
Node is able to run ES modules with cyclic dependencies without issue. I would expect the same when using the the loader-hook.

**Actual behaviour**
When specifying `--loader dd-trace/loader-hook.mjs`, the node process exits early with an exit code 13

**Steps to reproduce**
Here are a couple modules with a circular dependency, i.e. _a_ imports from _b_ and _b_ imports from _a_.

Running `node a.mjs` works as expected, producing output `testB\ntestA` and exiting with code 0.
Running `node --loader dd-trace/loader-hook.mjs a.mjs` prints out the standard Custom ESM Loaders warning but then silently exits with code 13 without executing the functions.

_a.mjs_
```js
import { testB } from './b.mjs';

export function testA() {
        console.log("testA");
}

testB();
```

_b.mjs_
```js
import { testA } from './a.mjs';

export function testB() {
        console.log("testB");
        testA();
}
```

**Environment**

* **Operation system:** MacOS 12.6
* **Node.js version:** v18.17.1
* **Tracer version:**  dd-trace 4.13.1
* **Agent version:** n/a
* **Relevant library versions:** n/a

**Comment by ChrisBellew** [comment]
I'm also getting this. +1 request for fix :pray:

**Comment by vecerek** [comment]
Same, please fix 🙇

**Comment by suhjohn** [comment]
@juan-fernandez @rochdev @tlhunter @simon-id

**Comment by simon-id** [comment]
It looks like a fix was merged in `import-in-the-middle` ? @tlhunter is this fixed ?

**Comment by tlhunter** [comment]
Yeah that's true, this should be working in recent versions of the tracer. @pwwolf can you confirm if this is still an issue?

**Comment by theodormarcu** [comment]
I believe that https://github.com/DataDog/import-in-the-middle/pull/36 didn't fully fix the issue. 

It looks like it was also reverted (see https://github.com/DataDog/import-in-the-middle/pull/48). I tried a version of the library that supposedly contained the fix and it didn't work though. I verified that exit code 13 was still being returned.

It would be great if this was fixed soon! As more and more packages start only shipping ESM-compatible versions, it's very hard to continue using a commonjs package.

**Comment by simon-id** [comment]
We just merged an update of `import-in-the-middle` that includes a fix for circular dependencies: https://github.com/nodejs/import-in-the-middle/pull/181

**Comment by simon-id** [comment]
I've tried running the snippet in the original post, and it looks like it still gives an error:
```
$ node --import ./dd-trace-js/register.js a.mjs
testB
file:///home/simon/workspaces/dd/b.mjs:5
        testA();
        ^

ReferenceError: Cannot access 'testA' before initialization
    at testB (file:///home/simon/workspaces/dd/b.mjs:5:9)
    at file:///home/simon/workspaces/dd/a.mjs:7:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.13.1
```

**Comment by simon-id** [comment]
@alvarosevilla95 did the patch make any difference to you ?

**Comment by alvarosevilla95** [comment]
Hey @simon-id, sorry I think I may have mistakenly grouped to different problems. The error I saw getting resolved after forcing  the new version of import-in-the-middle looks like this:

```
file:///Users/alvaro/Developer/labs/node_modules/.pnpm/web3-eth-abi@4.4.1_typescript@5.7.3_zod@3.24.1/node_modules/web3-eth-abi/lib/esm/coders/base/index.js?iitm=true:6
const _ = Object.assign(
                 ^

ReferenceError: decodeTuple is not defined
    at Function.assign (<anonymous>)
    at file:///Users/alvaro/Developer/labs/node_modules/.pnpm/web3-eth-abi@4.4.1_typescript@5.7.3_zod@3.24.1/node_modules/web3-eth-abi/lib/esm/coders/base/index.js?iitm=true:6:18
```

The error occurs on 1.13.0 but not on 1.13.1. I had concluded the error was related to iitm circular import handling in the past ( (can't remember why, it was a few months ago 😓), and given it got fixed on the exact version that introduced the circular import fix I assumed it would probably apply here too, but looks like I'm wrong

**Comment by alvarosevilla95** [comment]
fwiw just replicated the demo and I also reproduce the problem. So indeed I was to fast to claim the new version would help here. But it definitely fixes some loading issues, as the error I shared above. Apologies for the confusion 😅

**Comment by simon-id** [comment]
Ok no worries! I'm glad your specific issue was resolved at least.
For everyone else subscribed to this issue: false alert, the issue persists.
