### ISSUE TITLE
[Next.js] TypeError: Cannot read properties of undefined (reading 'url')

### ISSUE THREAD

**Issue by apadiyar-chwy** [DataDog/dd-trace-js#3682]
Received following error when loading page from app folder.
`
TypeError: Cannot read properties of undefined (reading 'url')
    at NextPlugin.pageLoad (webpack://hello/./node_modules/dd-trace/packages/datadog-plugin-next/src/index.js?:89:27)
    at eval (webpack://hello/./node_modules/dd-trace/packages/datadog-plugin-next/src/index.js?:17:55)
    at Subscription._handler (webpack://hello/./node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js?:14:9)
    at Channel.publish (node:diagnostics_channel:54:9)
    at NextNodeServer.findPageComponents (webpack://hello/./node_modules/dd-trace/packages/datadog-instrumentations/src/next.js?:86:23)
    at NextNodeServer.renderPageComponent (/Users/jack/hello/node_modules/next/dist/server/base-server.js:1579:35)
    at NextNodeServer.renderPageComponent (/Users/jack/hello/node_modules/next/dist/server/next-server.js:410:22)
`

**Environment**

* **Operation system:** mac ventura
* **Node.js version:** 16.11.1
* **Tracer version:** 4.16.0
* **Agent version:** : Compile time error
* **Relevant library versions:** Next Js version: 13.5.1

**Comment by sabrenner** [comment]
Hi @apadiyar-chwy, thanks for reporting this issue! I went to try and reproduce the issue, but it seems Next.js 13.5.1 is incompatible with Node 16.11.1, stating it needs a minimum of 16.14.0. If you could upgrade your Node versions and verify the issue still exists, that would be helpful. Thanks!

**Comment by tamarasaurus** [comment]
Hi @sabrenner @apadiyar-chwy I have the same issue while being on node `v16.19.0`, dd-trace `v4.16.0` and next `v13.5.4` both on the dev and production servers

**Comment by sabrenner** [comment]
@tamarasaurus Thanks for this clarification! I still wasn't able to reproduce this on my end, and our tests don't catch it either - could you provide more context on the setup of your project that produces this error? Are you using the `pages` or `app` directory? Is the error only when loading a page, or is it for API endpoints as well? If you're able to provide a small reproduction app that'd be great, but hopefully not necessary. Just some more context would be awesome!

**Comment by tamarasaurus** [comment]
@sabrenner So I set up a new NextJS v13.5.4 project from scratch using `pages` with dd-trace installed and ran the dev server like this:
```
node --require dd-trace/init ./node_modules/.bin/next dev
``` 
and I didn't have the error. When I added a middleware which didn't do anything except logging is when I started seeing the error:
```
import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

export function middleware(request: NextRequest) {
  console.log(request.url)
  return NextResponse.next()
}
```
```
 ⨯ uncaughtException: TypeError: Cannot read properties of undefined (reading 'url')
    at NextPlugin.pageLoad (/Users/tamara/code/dd-trace-url/dd-url/node_modules/dd-trace/packages/datadog-plugin-next/src/index.js:89:27)
    at /Users/tamara/code/dd-trace-url/dd-url/node_modules/dd-trace/packages/datadog-plugin-next/src/index.js:17:55
    at Subscription._handler (/Users/tamara/code/dd-trace-url/dd-url/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:14:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at /Users/tamara/code/dd-trace-url/dd-url/node_modules/dd-trace/packages/datadog-instrumentations/src/next.js:142:67
    at instrument (/Users/tamara/code/dd-trace-url/dd-url/node_modules/dd-trace/packages/datadog-instrumentations/src/next.js:115:33)
    at serveStatic (/Users/tamara/code/dd-trace-url/dd-url/node_modules/dd-trace/packages/datadog-instrumentations/src/next.js:141:12)
    at handleRequest (/Users/tamara/code/dd-trace-url/dd-url/node_modules/next/dist/server/lib/router-server.js:318:63)
    at async requestHandlerImpl (/Users/tamara/code/dd-trace-url/dd-url/node_modules/next/dist/server/lib/router-server.js:394:13)
    at async Server.requestListener (/Users/tamara/code/dd-trace-url/dd-url/node_modules/next/dist/server/lib/start-server.js:151:13)
```

I created a repo to reproduce the issue here:  https://github.com/tamarasaurus/dd-trace-url

**Comment by sabrenner** [comment]
@tamarasaurus Thanks for this! I've spent part of today looking into it, and as far as I can tell, Next.js has recently changed how the middleware -> page/API flow works. While before it was two consecutive operations (or seemingly so, since the way we traced it would have an additional `next.request` span without any route/page name attributed), it has changed to be the page/API handler flows off of the middleware logic by the middleware logic [throwing an error internal to Next.js](https://github.com/vercel/next.js/issues/55752). While this works fine for them, it means [we stop tracing the call "prematurely"](https://github.com/DataDog/dd-trace-js/blob/36f0d8e48261c6c767b32f56d12360db6261c480/packages/datadog-instrumentations/src/next.js#L131C12-L131C12), and end the span before the page/API request handler is called. Then, when that handler is called, we don't trace it, as [we check not to trace the same request](https://github.com/DataDog/dd-trace-js/blob/36f0d8e48261c6c767b32f56d12360db6261c480/packages/datadog-instrumentations/src/next.js#L117). However, since we still wrap `findPageComponents` without tracing, we try to attach the page name (ie `/api/[blob]/[blob2]` without a request object as a context, and break.

I plan on fixing this by checking if the request is a middleware request, and if so, not tracing it. This will result in _just_ tracing actual endpoint logic in the request cycle (leaving out middleware entirely) until we can find a better solution on our side for interacting with Next.js middleware.

Wanted to keep this transparent with you (and this thread) - I'll try to have the fix up soon and in the next release of the tracer!

**Comment by endrureza** [comment]
is this happening when you are using the old nextjs api routes handle or new one ? i experience the same when i'm using new api route handling like `app/api/route.js`

**Comment by mstroiu** [comment]
@endrureza Happens in both old and new apparently.

@JonShort the only solution is to wait for the fix @sabrenner mentioned.

**Comment by sabrenner** [comment]
Hi all, thanks for your patience here. I just merged this change in, and it should be in the next release. Anyone using newer versions of Next.js (>=13.5, and I think above 14 now as well) should not only not get the error in the original post for this issue, but also not see false errors on 200 requests. Feel free to continue commenting on this thread once the release lands, or re-open the issue or mention it in another if issues related to this still happen!

**Comment by jeremypress** [comment]
hey @sabrenner , we're still seeing this on next 12 after upgrading dd-trace. Is that expected until we upgrade?

**Comment by sabrenner** [comment]
@jeremypress thanks for noting this, I will give this a try and see if I can recreate & address this issue for Next.js 12.x. Is anyone else having this issue as well, or has it been fixed for newer versions of Next.js?

**Comment by JonShort** [comment]
@sabrenner I've seen it fixed in next 14 apps since the dd-trace update 👍

Anecdotally the DD metrics seem to have less noise too (no more generic "GET" spans)

So a big thanks for your efforts fixing this🥇

**Comment by jeremypress** [comment]
> @jeremypress thanks for noting this, I will give this a try and see if I can recreate & address this issue for Next.js 12.x. What specific version of Next are you using, and are you using middleware? I didn't think this to be expected at all with Next.js 12
> 
> Additionally, is anyone else having this issue as well, or has it been fixed for newer versions of Next.js?

no middleware, but we do host next within an express app that also has tracing.

we are on 12.3.1, and this seems to occur when we render our error page

**Comment by jeremypress** [comment]
I opened up https://github.com/DataDog/dd-trace-js/pull/3785 to handle this case

**Comment by iwan-uschka** [comment]
Can confirm that this issue disappeared after updating `dd-trace` to `v4.20.0`.

Setup:
- `next@14.0.1`
- `node@18.18.2`

**Comment by Benimation** [comment]
In our case, wrapping in `Suspense` mostly solved the problems.

We also needed to lazy-load a component that used `blueimp-load-image`, which also makes it fall back to the `Suspense` boundary. Posting it here in case others also need to import libraries that don't handle this out-of-the-box.
