### ISSUE TITLE
[BUG]: Memory leak in v5.45.0

### ISSUE THREAD

**Issue by fshafiee** [DataDog/dd-trace-js#5554]
### Tracer Version(s)

> 5.41.0

### Node.js Version(s)

20.10.0

### Bug Report

After upgrading from `v5.17.0` to `v5.43.0`, I noticed a memory leak across the services with dd-trace enabled and started receiving constant OOM alerts.

<img width="612" alt="Image" src="https://github.com/user-attachments/assets/2cbe4853-19ef-4f16-91fb-a61a043729fe" />

Supposedly, [the leak was patched in `v5.44.0`](https://github.com/DataDog/dd-trace-js/issues/5394), but the issue still persists after upgrading to `v5.45.0`; The memory is still leaking and the OOMs are still happening with the same frequency.

<img width="624" alt="Image" src="https://github.com/user-attachments/assets/12c24284-d0ce-487f-8883-4e24c7a2b5e4" />

The charts are captured from a background process that processes a stream of events with a fixed rate and is not subject to burst workloads (as is evident from the first graph).

I have downgraded to v5.40.0 as [one user suggested to be leak-free](https://github.com/DataDog/dd-trace-js/issues/5394#issuecomment-2741082558). Will share the results once I have gathered enough data.

### Bundling

No Bundling

**Comment by fshafiee** [comment]
@naholyr thanks for saving the rest of us the headache of trying out the new patch.

Here are the results after downgrading from `v5.45.0` to `v5.40.0`. Nothing else changed in the codebase.
<img width="1604" alt="Image" src="https://github.com/user-attachments/assets/e4a17c1c-e88b-4182-89d8-76859b8f06bf" />

**Comment by naholyr** [comment]
I have two different issues I monitored on our side:

- A project on 5.42 had sever issues with HUGE output bandwidth leak (slowly increasing until restart), with similar cpu/memory  spikes ➡ upgrading to 5.46 has solved issues
- Another one on 5.45 has been said to have severe performance issues, but it's actually not backed by metrics

So I can confirm 5.46 **looks** good (not 100% sure as the leak cycles are quite long, but overnight it stayed stable), and versions already known to be crap (incl. 5.42) are bad. Not much to say on 5.45.

**Comment by fshafiee** [comment]
@naholyr v5.46.0 seems to be plagued as well. See https://github.com/DataDog/dd-trace-js/issues/5565. How is it holding up for you?

**Comment by Khaledinges** [comment]
Having same memory leaks with multiple versions 3.7.1, 3.9.0, 5.4.0, 5.4.1, 5.4.6, 5.4.8, I tried every optimization hint, OOM still here, datadog will be disabled in production.

**Comment by T-iny** [comment]
This seems fixed in v5.49.0 in our pods, but I did not get the fix comments from the release note.

**Comment by mnahkies** [comment]
We're still seeing sawtoothing memory / OOM crashes when I try v5.49.0. 

For us v5.28.0 works fine without leak, but I haven't exhaustively tested to figure out which version introduced it.

**Comment by BridgeAR** [comment]
@Khaledinges could you please contact our support for the issue you are facing? I think this needs a closer investigation of your settings.

**Comment by BridgeAR** [comment]
@fshafiee @mnahkies are you still seeing the issues with the latest version 5.50.0? The reports here overlap about different issues in different versions and it is difficult to know what issue exactly you are currently facing.

**Comment by BridgeAR** [comment]
I would like to once again sincerely apologize for the issues you all encountered, particularly since the first fixed releases included new unrelated problems that are now also fixed.

I’ll go ahead and mark this as resolved now. If you experience any similar issues with the latest version, please don’t hesitate to open a new ticket.

**Comment by mnahkies** [comment]
@BridgeAR I've just tested `v5.51.0` in our `dev` environment, and still see an issue. I've opened a more specific issue for this here, as it only applies to some of our deployments - https://github.com/DataDog/dd-trace-js/issues/5690

**Comment by fshafiee** [comment]
Hey @BridgeAR, thanks for the update.
I no longer see any leaks in terms of memory usage on `v5.50.0`.
